export interface PropertyUnit {
  unitId: number;
  propertyId: number;
  propertyFloorId: number;
  unitCode: string;
  unitNumber: string;
  unitName: string | null;
  unitTypeId: number;
  unitCategoryId: number | null;
  unitStatusId: number;
  area: number;
  areaUnitId: number;
  bedroomCount: number | null;
  bathroomCount: number | null;
  parkingCount: number | null;
  balconyCount: number | null;
  furnishedStatusId: number | null;
  viewTypeId: number | null;
  unitDescription: string | null;
  isRentable: boolean;
  isSaleable: boolean;
  isActive: boolean;
  createdBy: number;
  createdDtTm: string;
  modifiedBy: number | null;
  modifiedDtTm: string | null;
  propertyCode?: string | null;
  propertyName?: string | null;
  floorCode?: string | null;
  floorName?: string | null;
  unitTypeName?: string | null;
  unitCategoryName?: string | null;
  unitStatusName?: string | null;
  unitStatusCode?: string | null;
  areaUnitName?: string | null;
  furnishedStatusName?: string | null;
  viewTypeName?: string | null;
  blockReason?: string | null;
  currentTenantId?: number | null;
  currentTenantCode?: string | null;
  currentTenantName?: string | null;
  allocatedFrom?: string | null;
}
