/** Property master — scoped by TenantID + CompanyID. */
export interface Property {
  propertyId: number;
  tenantId: number;
  companyId: number;
  propertyCode: string;
  propertyName: string | null;
  propertyDisplayName: string | null;
  shortDescription: string | null;
  description: string | null;
  internalRemarks: string | null;
  propertyTypeIds: number[];
  propertyCategoryIds: number[];
  propertyUsageId: number | null;
  ownershipTypeId: number | null;
  propertyBrandId: number | null;
  supplierId: number | null;
  addressLine1: string | null;
  addressLine2: string | null;
  buildingName: string | null;
  buildingNumber: string | null;
  streetName: string | null;
  streetNumber: string | null;
  zoneNumber: string | null;
  countryId: number;
  stateId: number | null;
  cityId: number | null;
  areaId: number | null;
  locationId: number | null;
  postalCode: string | null;
  poBox: string | null;
  landmark: string | null;
  latitude: number | null;
  longitude: number | null;
  googlePlaceId: string | null;
  googleMapUrl: string | null;
  plusCode: string | null;
  timeZoneId: number | null;
  /** YYYY-MM-DD */
  openingDate: string | null;
  /** YYYY-MM-DD */
  closingDate: string | null;
  rating: number | null;
  starRating: number | null;
  isFeatured: boolean;
  isPublished: boolean;
  isActive: boolean;
  createdBy: number | null;
  createdDtTm: string;
  modifiedBy: number | null;
  modifiedDtTm: string | null;
  companyName?: string;
  propertyTypeNames: string[];
  propertyCategoryNames: string[];
  propertyUsageName?: string;
  ownershipTypeName?: string;
  propertyBrandName?: string;
  countryName?: string;
  cityName?: string;
}
