import {
  LayoutDashboard,
  Users,
  CalendarCheck,
  Building2,
  Network,
  Briefcase,
  Receipt,
  BarChart3,
  Settings,
  TrendingUp,
  ClipboardCheck,
  BedDouble,
  Package,
  MapPinned,
  Wallet,
  CreditCard,
  ShieldCheck,
  UserPlus,
  Plus,
  type LucideIcon,
} from "lucide-react";

/** Maps icon name strings stored in config (MENU_ITEMS, dashboard widgets, quick actions) to their component. */
export const ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  Users,
  CalendarCheck,
  Building2,
  Network,
  Briefcase,
  Receipt,
  BarChart3,
  Settings,
  TrendingUp,
  ClipboardCheck,
  BedDouble,
  Package,
  MapPinned,
  Wallet,
  CreditCard,
  ShieldCheck,
  UserPlus,
  Plus,
};
